# Generated by Django 3.2.8 on 2022-09-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.PositiveSmallIntegerField()),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('identification', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('paternalSurname', models.CharField(max_length=35)),
                ('maternalSurname', models.CharField(max_length=35)),
                ('names', models.CharField(max_length=35)),
                ('dateBirth', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('validity', models.BooleanField(default=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.career')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollmentDate', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student')),
            ],
        ),
    ]
