# Generated by Django 3.2.8 on 2022-10-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identification',
            field=models.BigIntegerField(unique=True, verbose_name='Identificación'),
        ),
    ]
