# Generated by Django 3.2.8 on 2022-09-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='career',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='career',
            name='duration',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(max_length=100, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de matriculación'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='student',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.career', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateBirth',
            field=models.DateField(verbose_name='Fecha de nacimento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='identification',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='student',
            name='maternalSurname',
            field=models.CharField(max_length=35, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='names',
            field=models.CharField(max_length=35, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paternalSurname',
            field=models.CharField(max_length=35, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='validity',
            field=models.BooleanField(default=True, verbose_name='Vigencia'),
        ),
    ]
