# Generated by Django 3.2.8 on 2022-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_auto_20220927_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
